import dj_database_url
import os

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zu6c4q@1(u3fi*84n!m^6(slidgfl=fsdd_s0%lea-1k+ij+q9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['truonghong.fortiddns.com', '192.168.20.230', 'localhost', '127.0.0.1', '*']
# Sửa lại thành thế này (Thêm HTTP và HTTPS, bỏ port 1989 nếu Nginx đang dùng port 80/443 chuẩn)
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.20.230',
    'http://192.168.20.230:1989',
    'http://truonghong.fortiddns.com',
    'http://truonghong.fortiddns.com:1989',
    'https://truonghong.fortiddns.com',
    'https://truonghong.fortiddns.com:1989'
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'monitor.middleware.ActiveUserMiddleware',
]
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CẤU HÌNH ĐƯỜNG DẪN ĐĂNG NHẬP
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/map/1/'

# ==========================================
# CẤU HÌNH GIAO DIỆN JAZZMIN BỔ SUNG
# ==========================================
JAZZMIN_SETTINGS = {
    # 1. Đổi tiêu đề góc trái trên cùng
    "site_brand": "NOC Dashboard",
    "site_header": "Dashboard",
    "site_title": "NOC Dashboard Admin",
    "hide_models": ["auth.user", "auth.group"],
    # 2. Khai báo file CSS tùy chỉnh cho hiệu ứng Neon
    "custom_css": "css/admin_custom.css",

    # 3. Tạo menu tĩnh gom nhóm Công ty
    "custom_links": {
        "monitor": [
            {
                "name": "Thiết bị: AIMax", 
                "url": "/admin/monitor/device/?company__id__exact=1", 
                "icon": "fas fa-desktop",
            },
            {
                "name": "Thiết bị: KingWay", 
                "url": "/admin/monitor/device/?company__id__exact=2", 
                "icon": "fas fa-server",
            }
        ]
    },
}
