server {
    listen 80;
    server_name 192.168.20.230 truonghong.fortiddns.com;
    location / {
        proxy_pass http://backend:7000;  # Tên dịch vụ là backend, cổng là 7000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
