# Generated by Django 4.2 on 2026-04-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('telegram_chat_id', models.CharField(help_text='ID nhóm Telegram', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Địa chỉ IP')),
                ('device_type', models.CharField(choices=[('FW', 'Firewall'), ('CSW', 'Core Switch'), ('ASW', 'Access Switch'), ('PC', 'Máy tính'), ('CAM', 'Camera'), ('SRV', 'Server')], default='PC', max_length=3)),
                ('uplink_port', models.CharField(blank=True, max_length=50, verbose_name='Cổng trên thiết bị cha')),
                ('local_port', models.CharField(blank=True, max_length=50, verbose_name='Cổng tại thiết bị này')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitor.company')),
                ('parent_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='monitor.device', verbose_name='Thiết bị cha (Uplink)')),
            ],
        ),
    ]
