# Generated by Django 4.2 on 2026-04-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/', verbose_name='Bản vẽ mặt bằng'),
        ),
    ]
