# Generated by Django 4.2 on 2026-04-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_company_floor_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='parent_device',
        ),
        migrations.AddField(
            model_name='device',
            name='uplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlinks', to='monitor.device', verbose_name='Thiết bị cha (Uplink)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/', verbose_name='Sơ đồ mặt bằng'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('FW', 'Firewall'), ('CSW', 'Core Switch'), ('ASW', 'Access Switch'), ('PC', 'Máy tính'), ('CAM', 'Camera'), ('SRV', 'Server')], default='PC', max_length=5),
        ),
    ]
