# Generated by Django 4.2 on 2026-04-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_device_parent_device_device_uplink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Thiết bị Demo (Giữ Online)'),
        ),
    ]
