# Generated by Django 4.2 on 2026-04-06 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0004_device_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng được xem'),
        ),
    ]
