# Generated by Django 4.2 on 2026-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_company_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='local_port',
        ),
        migrations.AddField(
            model_name='device',
            name='device_port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cổng tại thiết bị'),
        ),
    ]
