# Generated by Django 4.2 on 2026-04-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_device_local_port_device_device_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Điểm bẻ cáp'),
        ),
    ]
