# Generated by Django 4.2 on 2026-04-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_device_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='company',
            name='admin_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Telegram Admin (Duyệt quyền)'),
        ),
    ]
