# Generated by Django 4.2 on 2026-04-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_company_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực (Bản vẽ)')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='floorplans/', verbose_name='Ảnh bản vẽ nền')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='monitor.company')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='floorplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.floorplan', verbose_name='Thuộc bản vẽ'),
        ),
    ]
