# Generated by Django 4.2 on 2026-04-11 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_floorplan_device_floorplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Công ty', 'verbose_name_plural': 'Danh sách Công ty'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Thiết bị', 'verbose_name_plural': 'Danh sách Thiết bị'},
        ),
        migrations.AlterModelOptions(
            name='floorplan',
            options={'verbose_name': 'Khu vực / Bản vẽ', 'verbose_name_plural': 'Danh sách Khu vực'},
        ),
        migrations.AddField(
            model_name='floorplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả thêm'),
        ),
        migrations.AlterField(
            model_name='company',
            name='admin_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Telegram Admin'),
        ),
        migrations.AlterField(
            model_name='company',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/', verbose_name='Sơ đồ mặt bằng gốc'),
        ),
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitor.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_usage',
            field=models.FloatField(default=0.0, verbose_name='CPU (%)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('FW', 'Firewall'), ('CSW', 'Core Switch'), ('ASW', 'Access Switch'), ('PC', 'Máy tính'), ('CAM', 'Camera'), ('SRV', 'Server')], default='PC', max_length=5, verbose_name='Loại thiết bị'),
        ),
        migrations.AlterField(
            model_name='device',
            name='floorplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='monitor.floorplan', verbose_name='Thuộc khu vực/Bản vẽ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Trạng thái Online'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần cuối nhìn thấy'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram_usage',
            field=models.FloatField(default=0.0, verbose_name='RAM (%)'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='monitor.company', verbose_name='Thuộc Công ty'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khu vực (VD: Xưởng A, Tầng 1)'),
        ),
    ]
