# Generated by Django 4.2 on 2026-04-11 07:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitor', '0010_alter_company_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'User Dashboard',
                'verbose_name_plural': 'Quản lý Người Dùng',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
