# Generated by Django 4.2 on 2026-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_userdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdashboard',
            options={'verbose_name': 'User Dashboard', 'verbose_name_plural': 'Danh Sách Người Dùng'},
        ),
        migrations.AddField(
            model_name='device',
            name='x_overview',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tọa độ X (Tất cả)'),
        ),
        migrations.AddField(
            model_name='device',
            name='y_overview',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tọa độ Y (Tất cả)'),
        ),
    ]
