# Generated by Django 4.2 on 2026-04-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_userdashboard_options_device_x_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='x_overview',
            new_name='pos_x_overview',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='y_overview',
            new_name='pos_y_overview',
        ),
    ]
